[package]
name = "fend"
version.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "../README.md"

[dependencies]
ctrlc = "3.4.4"
fend-core.workspace = true
home = "0.5.9"
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
rustyline = { version =  "14.0.0", default-features = false, features = ["with-file-history", "custom-bindings"] }
serde = { version = "1.0.203", default-features = false }
toml = { version = "0.8.14", default-features = false, features = ["parse"] }
minreq = { version = "2.11.2", default-features = false, optional = true }
num-format = "0.4.4"
locale-codes = "0.3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[features]
native-tls = [ "dep:minreq", "minreq/https-native" ]
rustls = [ "dep:minreq", "minreq/https-rustls-probe" ]
default = [ "native-tls" ]
